import json
from datetime import datetime
import boto3
from botocore.exceptions import ClientError

def summarize_text_with_claude(prompt: str) -> str:
    """
    Summarizes the given prompt using Anthropic's Claude model via Amazon Bedrock.

    :param prompt: The text to be summarized.
    :return: The summary generated by Claude.
    """

    client = boto3.client("bedrock-runtime")


    prompt = "summarize the following text ... \n" + prompt

    # get the correct modelId for eu-west-1 region
    # https://github.com/danny-avila/LibreChat/discussions/4571
    kwargs = {
        "modelId": "eu.anthropic.claude-3-5-sonnet-20240620-v1:0",
        "contentType": "application/json",
        "accept": "application/json",
        "body": json.dumps({
            "anthropic_version": "bedrock-2023-05-31",
            "max_tokens": 1000,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {"type": "text", 
                         "text": prompt},
                    ],
                }
            ],
        }),
    }

    try:
        response = client.invoke_model(**kwargs)

        response_body = response["body"].read()
        result = json.loads(response_body)
        summary = result.get("content", "")[0]['text']

        return summary

    except Exception as e:
        print("Error calling Claude via Bedrock:", e)
        raise
    


def handler(event, context):
    """
    Lambda function to retrieve a text file from S3 using the provided bucket and object key,
    summarize the text using Anthropic's Claude model via Amazon Bedrock, and return the summary.

    Expected event payload:
    {
        "bucket": "<bucket-name>",
        "object_key": "<object-key>",
        "app_name": "...",        # optional additional info
        "environment": "...",       # optional additional info
        "user_id": "...",           # optional additional info
        "task_id": "...",           # optional additional info
        "filename": "..."           # optional additional info
    }
    """
    s3_client = boto3.client("s3")
    dynamodb = boto3.resource("dynamodb")
    table = dynamodb.Table("ProcessStateTable")

    try:
        bucket = event.get("bucket")
        object_key = event.get("object_key")

        print(f"bucket: {bucket}")
        print(f"object_key: {object_key}")
        
        if not bucket or not object_key:
            raise ValueError("Missing bucket or object_key in the event payload.")

        s3_response = s3_client.get_object(Bucket=bucket, Key=object_key)
        text = s3_response["Body"].read().decode("utf-8")
        print(f"Retrieved text from s3://{bucket}/{object_key}")

        summary = summarize_text_with_claude(text)
        print("Summary:", summary)

        key_parts = object_key.split("/")
        if len(key_parts) != 8:
            raise ValueError("Unexpected object key format.")
        
        app_name, environment, resource_type, _, user_id, task_type, task_id, filename = key_parts
        # parsing this from object key might not be safe, prefer explicit payload parameters
        results_key = f"{app_name}/{environment}/results/account/{user_id}/summarize/{task_id}/{filename}"
        s3_client.put_object(Bucket=bucket, Key=results_key, Body=summary)

        print(f"Uploaded summary to s3://{bucket}/{results_key}")
        s3_link = f"s3://{bucket}/{results_key}"
        completed_date = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

        # Update the ProcessStateTable in DynamoDB.
        table.update_item(
            Key={
                "userId": user_id,
                "taskId": task_id
            },
            UpdateExpression="SET #s = :completed, results_s3_link = :link, completedDate = :date",
            ExpressionAttributeNames={
                "#s": "status"
            },
            ExpressionAttributeValues={
                ":completed": "completed",
                ":link": s3_link,
                ":date": completed_date,
            }
        )

        return {
            "statusCode": 200,
            "summary": summary,
            "results_s3_link": s3_link,
            "completedDate": completed_date
        }
    
    except KeyError as e:
        print(f"KeyError: {e}. Event: {json.dumps(event)}")
        raise RuntimeError("Invalid S3 event structure.")
    except ClientError as e:
        print("Error accessing resources:", e)
        return {
            "statusCode": 500,
            "error": f"Error accessing resources {e}"
        }
    except Exception as e:
        print("Unexpected error:", e)
        return {
            "statusCode": 500,
            "error": str(e)
        }