import json
import boto3
from botocore.exceptions import ClientError

def summarize_text_with_claude(prompt: str) -> str:
    """
    Summarizes the given prompt using Anthropic's Claude model via Amazon Bedrock.

    :param prompt: The text to be summarized.
    :return: The summary generated by Claude.
    """

    client = boto3.client("bedrock-runtime")


    prompt = "summarize the following text ... \n" + prompt

    # get the correct modelId for eu-west-1 region
    # https://github.com/danny-avila/LibreChat/discussions/4571
    kwargs = {
        "modelId": "eu.anthropic.claude-3-5-sonnet-20240620-v1:0",
        "contentType": "application/json",
        "accept": "application/json",
        "body": json.dumps({
            "anthropic_version": "bedrock-2023-05-31",
            "max_tokens": 1000,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {"type": "text", 
                         "text": prompt},
                    ],
                }
            ],
        }),
    }

    try:
        response = client.invoke_model(**kwargs)

        response_body = response["body"].read()
        result = json.loads(response_body)
        summary = result.get("content", "")[0]['text']

        return summary

    except Exception as e:
        print("Error calling Claude via Bedrock:", e)
        raise
    

def handler(event, context):
    """
    Lambda function to retrieve a text file from S3 using the provided bucket and object key,
    summarize the text using Anthropic's Claude model via Amazon Bedrock, and return the summary.

    Expected event payload:
    {
        "bucket": "<bucket-name>",
        "object_key": "<object-key>",
        "app_name": "...",        # optional additional info
        "environment": "...",       # optional additional info
        "user_id": "...",           # optional additional info
        "task_id": "...",           # optional additional info
        "filename": "..."           # optional additional info
    }
    """
    s3_client = boto3.client("s3")
    
    try:
        bucket = event.get("bucket")
        object_key = event.get("object_key")
        if not bucket or not object_key:
            raise ValueError("Missing bucket or object_key in the event payload.")

        s3_response = s3_client.get_object(Bucket=bucket, Key=object_key)
        text = s3_response["Body"].read().decode("utf-8")
        print(f"Retrieved text from s3://{bucket}/{object_key}")

        summary = summarize_text_with_claude(text)
        print("Summary:", summary)

        return {
            "statusCode": 200,
            "summary": summary
        }
        
    except ClientError as e:
        print("Error accessing resources:", e)
        return {
            "statusCode": 500,
            "error": f"Error accessing resources {e}"
        }
    except Exception as e:
        print("Unexpected error:", e)
        return {
            "statusCode": 500,
            "error": str(e)
        }